name: Test artifact V4
on: [workflow_dispatch, pull_request]
jobs:
  Artifact-Upload:
    runs-on: ubuntu-latest
    steps:
    - name: Some annotation
      run: |
        echo "::error::Some annotation"
    
    - name: Create file
      run: |
        mkdir content
        cd content
        head -c 100 </dev/urandom >file1.zip
        touch -d "$(date -R -r file1.zip) - 2 hours" file1.zip
    - name: Upload First
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: |
          content/*
        retention-days: 1
  
      
  
