name: Test artifact V4
on: [workflow_dispatch, pull_request]
jobs:
  Artifact-Upload:
    runs-on: ubuntu-latest
    steps:
    
    - name: Show me some file
      run: |
        cd /etc
        ls
  
  
  
      
  
