name: Test artifact V4
on: [workflow_dispatch, pull_request]
jobs:
  Artifact-Upload:
    runs-on: ubuntu-latest
    steps:
    
    - name: Create file
      run: |
        cd /
        echo hello > file.txt
    
    - name: Upload Artifact v4
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact-v4
        path: /file.txt
        retention-days: 1
  
  
      
  
