name: Test artifact V4
on: [workflow_dispatch, pull_request]
jobs:
  Artifact-Upload:
    runs-on: ubuntu-latest
    steps:
    - name: Some annotation
      run: |
        echo "::error::Some annotation"
    
    - name: Create large file
      run: |
        mkdir content
        cd content
        head -c 10000 </dev/urandom >file1.zip
        cd ..
    - name: Upload First
      uses: actions/upload-artifact@v4
      with:
        name: |
            line 1
            line 2
        path: |
          content/*
        retention-days: 1
  
      
  
