name: Test_Artifact_V2
on: workflow_dispatch
jobs:
  Artifact-Upload:
    runs-on: ubuntu-latest
    steps:
    - name: Create 2zip files
      run: |
        mkdir content
        mkdir test
        head -c 300000000 </dev/urandom >content/file8.zip
        head -c 300000000 </dev/urandom >content/file2.zip
        
        echo "testing" > content/file3.txt
        echo "testing" > content/file4.txt
        echo "testing" > content/file5.txt
        echo "testing" > content/file6.txt
        echo "testing" > content/file7.txt
        
        wc -c content/*
    - name: Upload First
      uses: konradpabjan/upload-artifact@main
      with:
        name: my-artifact
        path: |
          content/*
        retention-days: 1
        
    - name: Upload Second
      uses: konradpabjan/upload-artifact@main
      with:
        name: my-artifact2
        path: |
          content/*
        retention-days: 1
        
  Artifact-Download:
    runs-on: ubuntu-latest
    needs: Artifact-Upload
    steps:
    - name: Download artifact
      uses: konradpabjan/download-artifact@main 
