name: Test_Artifact_V2
on: workflow_dispatch
jobs:
  Job-With-Artifact-Upload:
    runs-on: ubuntu-latest
    steps:
    - run: |
        mkdir testing
        cd testing
        mkdir file.abcdefg
        cd ..
        echo "This is a file to upload" > testing/file.abcdefg/test-123.txt
    - name: Upload artifact
      uses: konradpabjan/upload-artifact@main
      with:
        name: artifact
        path: testing/*
        retention-days: 15
      env:
        ACTIONS_STEP_DEBUG: true
