name: Test_Artifact_V2
on: workflow_dispatch
jobs:
  Job-With-Artifact-Upload:
    runs-on: ubuntu-latest
    steps:
    - name: Create 8000MB artifact
      run: |
        mkdir content
        mkdir test
        head -c 8000000000 </dev/urandom >content/file1.txt
        
        wc -c content/*
    - name: Upload First
      uses: konradpabjan/upload-artifact@main
      with:
        name: my-artifact
        path: |
          content/file1.txt
        retention-days: 1
      env:
        ACTIONS_STEP_DEBUG: true
        
    - uses: geekyeggo/delete-artifact@v1
      with:
        name: my-artifact
