name: Test_Artifact_V2
on: workflow_dispatch
jobs:
  Job-With-Artifact-Upload:
    runs-on: ubuntu-latest
    steps:
    - run: |
        mkdir content
        echo "hello 1" > content/file1.txt
        echo "hello 2" > content/file2.txt
        echo "bad file" > content/file3.txt
    - name: Upload all
      uses: actions/upload-artifact@v2.2.3
      with:
        name: My-Artifact
        path: |
          content/*.txt
          !content/file3.txt
        retention-days: 15
  Job-With-Artifact-Download:
    runs-on: Ubuntu-20.04
    needs: Job-With-Artifact-Upload
    steps:
    - name: Download all
      uses: actions/download-artifact@v2.0.9
      with:
        name: My-Artifact
    - name: Display contents
      run: |
        find 
