name: Test_Artifact_V2
on: workflow_dispatch
jobs:
  Job-With-Artifact-Upload:
    runs-on: ubuntu-latest
    steps:
    - run: |
        mkdir content
        head -c 1000000 </dev/urandom >content/file1.txt
        
        for i in {0..50000}
        do
          echo "Hello world repeating multiple times" >> content/file2.txt
        done
        
        echo "bad file" > content/file3.txt
        
        wc -c content/*
    - name: Upload First
      uses: konradpabjan/upload-artifact@main
      with:
        name: |
          multi-line
          artifact name
        path: content/file2.txt
        retention-days: 15
      env:
        ACTIONS_STEP_DEBUG: true
    - name: Upload Second
      uses: konradpabjan/upload-artifact@main
      with:
        name: 'artifact-name'
        path: content/file3.txt
        retention-days: 15
