name: Test artifact V3
on: [workflow_dispatch, pull_request]
jobs:
  Artifact-Upload:
    runs-on: ubuntu-latest
    steps:
    
    - name: Create file with content
      run: |
        for ((i=1;i<=10000;i++)) ; do echo "Hello World" >> file.txt ;  done
  
    - name: Upload Artifact v3
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: file.txt
        retention-days: 1
  
      
  
