name: Test artifact V4
on: [workflow_dispatch, pull_request]
jobs:
  Artifact-Upload:
    runs-on: ubuntu-latest
    steps:
    - name: Some annotation
      run: |
        echo "::error::Some annotation"
    
    - name: Create file
      run: |
        head -c 100 </dev/urandom >file
    - name: Upload First
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: file
        retention-days: 1
  
      
  
