name: Test_Artifact_V2
on: workflow_dispatch
jobs:
  Job-With-Artifact-Upload:
    runs-on: ubuntu-latest
    steps:
    - run: |
        mkdir content
        head -c 10000000 </dev/urandom >content/file1.txt
        echo "hello 2" > content/file2.txt
        echo "bad file" > content/file3.txt
    - name: Upload First
      uses: actions/upload-artifact@v2
      with:
        name: 'artifact name'
        path: content/file1.txt
        retention-days: 15
      env:
        ACTIONS_STEP_DEBUG: true
    - name: Upload Second
      uses: actions/upload-artifact@v2
      with:
        name: another-artifact
        path: content/file1.txt
        retention-days: 15
    - name: Upload all
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: content/file1.txt
        retention-days: 15
      env:
        ACTIONS_STEP_DEBUG: true
