name: Test_Artifact_V2
on: workflow_dispatch
jobs:
  Job-With-Artifact-Upload:
    runs-on: ubuntu-latest
    steps:
    - name: Create 2zip files
      run: |
        mkdir content
        mkdir test
        head -c 800000000 </dev/urandom >content/file1.zip
        head -c 800000000 </dev/urandom >content/file2.zip
        
        wc -c content/*
    - name: Upload First
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: |
          content/file1.zip
          content/file2.zip
        retention-days: 1
      env:
        ACTIONS_STEP_DEBUG: true
        
    - uses: geekyeggo/delete-artifact@v1
      with:
        name: my-artifact
