name: Test_Artifact_V2
on: [workflow_dispatch, pull_request]
jobs:
  Artifact-Upload:
    runs-on: ubuntu-latest
    steps:
    - name: Create large file
      run: |
        mkdir content
        cd content
        head -c 10000 </dev/urandom >file1.zip
        cd ..
    - name: Upload First
      uses: actions/upload-artifact@v2.2.4
      with:
        name: my-artifact
        path: |
          content/*
        retention-days: 1
  
        
  Artifact-Download:
    runs-on: ubuntu-latest
    needs: Artifact-Upload
    steps:
    - name: Sleep for 5 seconds
      run: |
        sleep 5
    - name: Download artifact
      uses: konradpabjan/download-artifact@main
      with:
        name: my-artifact
    - name: Testing
      run: |
        pwd
        ls *
  
