name: Test_Artifact_V2
on: [push]
jobs:
  Upload:
    runs-on: ubuntu-latest
    steps:
    - run: |
        mkdir fa1_app
        mkdir fa1_app/fa1
        mkdir fa2_app
        mkdir fa2_app/fa2
        echo "hello 1" > fa1_app/host.json
        echo "hello 2" > fa2_app/host.json
        echo "hi 1" > fa1_app/fa1/test.txt
        echo "hi 2" > fa2_app/fa2/test.txt
    - name: Upload all
      uses: actions/upload-artifact@v2
      with:
        name: FunctionApps
        path: |
          fa1_app
          fa2_app
  Verify_Artifact:
    needs: Upload
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt install tree
      - name: Download all
        uses: actions/download-artifact@v2
      - name: Display contents of artifact
        run: |
          tree .
