name: Test_Artifact_V2
on: [push]
jobs:
  v2-artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        mkdir -p to-upload/artifact
        mkdir download-dir
    - name: 'Upload artifact'	
      uses: actions/upload-artifact@konradpabjan/no-files-found
      with:
        path: |
          to-upload
    - name: 'Download artifact'
      id: 'testing'
      uses: actions/download-artifact@v2
    
    - name: 'Test output'
      run: echo ${{steps.testing.outputs.download-path}}
