name: Test_Artifact_V2
on: [push]
jobs:
  v2-artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        mkdir -p to-upload/artifact
        echo This is going to be a lot of text. Repeat Repeat. The Gzip size should be less than the original > to-upload/artifact/world.txt
    - name: 'Upload artifact'	
      uses: actions/upload-artifact@v2
      with:	
        name: 'First Artifact'
        path: to-upload/artifact/world.txt
        
    - name: 'Delete files'
      run: |
        rm -rf to-upload
        sudo apt-get install tree
        tree .
    
    - name: 'Download artifact'	
      uses: actions/download-artifact@v2
      with:	
        name: 'First Artifact'
        path: download-dir
    
    - name: "show"
      run: |
        tree . 
