name: Test_Artifact_V2
on: [push]
jobs:
  v2-artifacts:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo 'hello A' > A.txt
        echo 'hello b' > b.txt
        dd if=/dev/urandom of=sample.txt bs=64M count=4
        mkdir empty
    - name: 'Upload artifact'	
      uses: actions/upload-artifact@v2.1.4
      with:
        path: './empty'
    
