name: Test_Artifact_V2
on: [push]
jobs:
  v2-artifacts:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        mkdir -p to-upload/artifact
        mkdir empty-dir
    - name: 'Upload artifact'	
      uses: actions/upload-artifact@v2
      with:
        path: |
          ~/
    - name: 'Download artifact'
      id: 'testing'
      uses: actions/download-artifact@v2
    
    - name: 'Test output'
      run: echo ${{steps.testing.outputs.download-path}}
