name: Test_Artifact_V2
on: [push]
jobs:
  v2-artifacts:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo 'hello A' > A.txt
        echo 'hello a' > a.txt
        echo 'hello b' > b.txt
    - name: 'Upload artifact'	
      uses: actions/upload-artifact@konradpabjan/case-insensitivity
      with:
        path: './'
    - name: 'Download artifact'
      uses: actions/download-artifact@v2
      with:
        path: download-dir
    
    - name: 'Test'
      run: |
        ls -R
        cat download-dir/A.txt
        cat download-dir/a.txt
    
