name: Test_Artifact_V2
on: [push]
jobs:
  v2-artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        mkdir -p to-upload/artifact
        mkdir -p other/stuff
        echo Hello > to-upload/artifact/world.txt
        echo Hi > to-upload/A.txt
        echo Hi again > other/stuff/file.txt
        echo Nope > other/stuff/no.txt
        echo B > other/stuff/B.txt
    - name: 'Upload artifact'	
      uses: konradpabjan/upload-artifact@v2-preview
      with:
        path: |
          to-upload/artifact
          other/*
          !**/no.txt    
    - name: 'Delete files'
      run: |
        rm -rf to-upload
        sudo apt-get install tree
        tree .
    
    - name: 'Download artifact'	
      uses: actions/download-artifact@v2
      with:	
        path: .
    
    - name: "show"
      run: |
        tree . 
