name: Test_Artifact_V2
on: [push]
jobs:
  Upload:
    runs-on: ubuntu-latest
    steps:
    - run: |
        mkdir fa1_publish_output
        mkdir fa1_publish_output/fa1app
        mkdir fa2_publish_output
        mkdir fa2_publish_output/fa2app
        echo "hello 1" > fa1_publish_output/host.json
        echo "hello 2" > fa2_publish_output/host.json
        echo "hi 1" > fa1_publish_output/fa1app/test.txt
        echo "hi 2" > fa2_publish_output/fa2app/test.txt
    - name: Upload all
      uses: actions/upload-artifact@v2
      with:
        path: |
          fa1_publish_output
          fa2_publish_output
  Verify_Artifact:
    needs: Upload
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt install tree
      - name: Download all
        uses: actions/download-artifact@v2
      - name: Display contents of artifact
        run: |
          tree .
