name: Test_Artifact_V2
on: [push]
jobs:
  v2-artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        mkdir -p to-upload/artifact
        echo This is going to be a lot of text. Repeat Repeat. The Gzip size should be less than the original > to-upload/artifact/world.txt
        mkdir -p to-upload/artifact2
        echo hello2 > to-upload/artifact2/world2.txt
        cd to-upload
        for i in {000..5000}
        do
            echo hello! > "File${i}.txt"
        done
        dd if=/dev/urandom of=/to-upload/bigFile.txt bs=64M count=32
        mkdir download-dir
    - name: 'Upload artifact'	
      uses: actions/upload-artifact@konradpabjan/v2-fix-retries
      with:	
        name: 'First Artifact'
        path: to-upload
    
    - name: 'Download artifact'	
      uses: actions/download-artifact@v2
      with:	
        name: 'First Artifact'
        path: download-dir
    
    - name: 'Upload artifact again'	
      uses: actions/upload-artifact@konradpabjan/v2-fix-retries
      with:	
        name: 'Second Artifact'
        path: download-dir
