name: Test_Artifact_V2
on: [push]
jobs:
  Upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        filename: [file1,file2]
    steps:
    - run: |
        mkdir testfloder
        echo hey >> testfolder/{{matrix.filename}}.txt
    - name: Upload all
      uses: actions/upload-artifact@v2
      with:
        path: ./

  Create_PR:
    needs: Upload
    runs-on: ubuntu-latest
    steps:
      - name: Download all
        uses: actions/download-artifact@v2
      - name: Move the content of the directory to the root
        run: |
          rsync -a artifact/* ./
          rm -d -r artifact
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: UploadTest
          title: "[AUTO] upload test"
          labels: UploadTest
          branch: "UploadTest"
