name: Test_Artifact_V2
on: [push]
jobs:
  v2-artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        mkdir -p to-upload/artifact
        mkdir download-dir
        echo A > to-upload/artifact/A.txt
        echo B > to-upload/artifact/B.txt
        echo C > to-upload/artifact/C.txt
    - name: 'Upload artifact'	
      uses: actions/upload-artifact@v2
      with:
        path: |
          to-upload/**/[BCDE].txt
          to-upload/**/A.txt
          !**/A.txt
    - name: 'Download artifact'
      id: 'testing'
      uses: actions/download-artifact@konradpabjan/misc-improvements
      with:
        path: download-dir
    
    - name: 'Test output'
      run: echo ${{steps.testing.outputs.downloadPath}}
