name: Test_Artifact_V2
on: [push]
jobs:
  v2-artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        mkdir -p to-upload/artifact
        echo Hello > to-upload/artifact/world.txt
        echo Hi > to-upload/artifact/A.txt
        echo Hi again > to-upload/artifact/file.txt
    - name: 'Upload artifact'	
      uses: actions/upload-artifact@v2.1.0
      with:
        path: |
          to-upload/**/world.txt
          to-upload/**/file.txt
          !**/A.txt    
    - name: 'Delete files'
      run: |
        rm -rf to-upload
        sudo apt-get install tree
        tree .
    
    - name: 'Download artifact'	
      uses: actions/download-artifact@v2
      with:	
        path: .
    
    - name: "show"
      run: |
        tree . 
