name: Test_Artifact_V2
on: [push]
jobs:
  Upload:
    runs-on: ubuntu-latest
    steps:
    - run: |
        mkdir fa1_app
        mkdir fa1_app/fa1
        mkdir fa2_app
        mkdir fa2_app/fa2
        echo "hello 1" > fa1_app/host.json
        echo "hello 2" > fa2_app/host.json
        echo "hi 1" > fa1_app/fa1/test.txt
        echo "hi 2" > fa2_app/fa2/test.txt
    - name: This should skip
      if: ${{ github.event_name == 'pull_request'}}
      run: echo Some step that should be skipped
    - name: Test
      run: echo Hi there
    - name: Upload all
      uses: actions/upload-artifact@v2
      with:
        name: My-Artifact
        path: |
          fa1_app
          fa2_app
        retention-days: 15 
