name: Test_Artifact_V2
on: [push]
jobs:
  Upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        filename: [file1,file2]
    steps:
    - run: |
        mkdir testfolder
        echo hey >> testfolder/${{matrix.filename}}.txt
    - name: Upload all
      uses: actions/upload-artifact@v2
      with:
        path: ./

  Verify_Artifact:
    needs: Upload
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt install tree
      - name: Download all
        uses: actions/download-artifact@v2
      - name: Display contents of artifact
        run: |
          tree .
