  
name: Test_Artifact_V2
on: [push]
jobs:
  v2-artifacts:
    runs-on: [ubuntu-latest]
    env:
      name: my-artifact-name
    steps:
    - uses: actions/checkout@v2
    
    - run: |
        sudo apt-get install tree
        
    - run: |	
        mkdir download-v1-dir
        mkdir download-v2-master
        mkdir download-v2-updates
        touch node_modules/empty	
    - name: 'Upload artifact using v2'		
      uses: actions/upload-artifact@v2	
      with:		
        name: 'V2-Artifact-Upload'	
        path: node_modules/
        
    - run: cd download-v1-dir

    - name: 'Download artifact using v1'		
      uses: actions/download-artifact@v1
      with:		
        name: 'V2-Artifact-Upload'	
        
    - run: |
        tree ./
        cd ..
        cd download-v2-master

    - name: 'Download artifact using v2'		
      uses: actions/download-artifact@v2
      with:		
        name: 'V2-Artifact-Upload'	 
        
    - run: |
        tree ./
        cd ..
        cd download-v2-updates
    
    - name: 'Download artifact using v2 latest changes'		
      uses: actions/download-artifact@konradpabjan/updates-to-v2
      with:		
        name: 'V2-Artifact-Upload'	
        
    - run: tree ./
        
