  
name: Test_Artifact_V2
on: [push]
jobs:
  v2-artifacts:
    runs-on: [ubuntu-latest]
    env:
      name: my-artifact-name
    steps:
    - uses: actions/checkout@v2
    
    - run: |
        sudo apt-get install tree
        
    - run: |	
        mkdir download-dir-folder	
        mkdir download-dir-no-folder
        touch node_modules/empty	
    - name: 'Upload artifact using v2'		
      uses: actions/upload-artifact@v2	
      with:		
        name: 'V1-Artifact-Upload'	
        path: node_modules/	

    - name: 'Download artifact using v2 no folder'		
      uses: actions/download-artifact@konradpabjan/v2-updates
      with:		
        name: 'V1-Artifact-Upload'	
        path: download-dir-no-folder
        
    - run: tree download-dir-no-folder  

    - name: 'Download artifact using v2 with folder'		
      uses: actions/download-artifact@konradpabjan/v2-updates
      with:		
        name: 'V1-Artifact-Upload'	
        path: download-dir-folder
        artifact-folder: true
        
    - run: tree download-dir-folder
        
