name: Test_Artifact_V2
on: [push]
jobs:
  v2-artifacts:
    runs-on: [ubuntu-latest]
    env:
      name: my-artifact-name
    steps:
    - uses: actions/checkout@v2
    - run: |
        mkdir download-dir1
        mkdir download-dir2
    - name: 'Upload artifact using v2'	
      uses: actions/upload-artifact@v1
      with:	
        name: 'V2-Artifact-Upload'
        path: node_modules/*
    
    - name: 'Download artifact using v2'	
      uses: actions/download-artifact@v2
      with:	
        name: 'V2-Artifact-Upload'
        path: download-dir
    
    - name: 'Upload artifact using v2 again'	
      uses: actions/upload-artifact@v2
      with:	
        name: 'V2-Artifact-Upload-Again'
        path: download-dir/**/bin/*
    
